name: sad excuse for a test script

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**.cpp'
      - '**.h'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: set up the runner owo
      run: 'mkdir build'
      
    - name: "runner setup: the sequel"
      run: 'mkdir build/obj'
      
    - name: build the thing
      run: make
